// <auto-generated />
using System;
using EasyBilling.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyBilling.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202154109_AddClientSeeding")]
    partial class AddClientSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyBilling.Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CUI")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Company_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f5d9b2-1e34-4d5c-92a4-1d9c4c7b0151"),
                            Address = "Targu-Jiu, str. Spectaculosilor 14",
                            Bank = "BCR",
                            CUI = "RO12345678",
                            Company_Id = new Guid("c13dbb54-9fc5-4c72-92df-c47e6dfcce21"),
                            IBAN = "RO49BCRL00001012345678",
                            Name = "SC Spectacol SRL",
                            RegNumber = "J40/1234/2010"
                        },
                        new
                        {
                            Id = new Guid("b7c89fa1-6bd2-4c26-a7ea-3b2cdb0f9e62"),
                            Address = "Tismana",
                            Bank = "BT",
                            CUI = "RO27833491",
                            Company_Id = new Guid("de45bb29-fb3f-4c53-b9a0-87d13a6cc920"),
                            IBAN = "RO27BTRL0000123456789012",
                            Name = "Pandurii Tismana",
                            RegNumber = "J12/567/2015"
                        });
                });

            modelBuilder.Entity("EasyBilling.Domain.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VatCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("EasyBilling.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Client_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Client_Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a3f1b2c6-5d7a-4c89-bc36-9e7f2a51d101"),
                            Client_Id = new Guid("e8c9d14f-3df0-4ab5-9a72-6c1f4bb3a202"),
                            Client_Secret = "admin123",
                            Email = "admin@gmail.com",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("5b7d8e03-9f3e-4c28-ae10-2a6f7c934303"),
                            Client_Id = new Guid("c2a4f8b1-6e5d-4f17-91bb-0f92b74f4404"),
                            Client_Secret = "user123",
                            Email = "user@gmail.com",
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
